FROM nginx:alpine

# Remove configuração padrão
RUN rm /etc/nginx/conf.d/default.conf

# Copia nossa configuração
COPY nginx.conf /etc/nginx/nginx.conf

# Expõe a porta
EXPOSE 3000

# Inicia o Nginx
CMD ["nginx", "-g", "daemon off;"]

