packages:
  - "frontend"
  - "backend"
overrides:
  devalue: "latest"
  esbuild: ">=0.28.1"
  fast-uri: ^3.1.2
  qs: ">=6.15.2"
  yaml: ^2.8.3
onlyBuiltDependencies:
  - "esbuild"
  - "sharp"
  - "bcryptjs"

pmOnFail: ignore

allowBuilds:
  esbuild: true
  sharp: true
